stryker4s {
  mutate = [
    "src/main/scala/controller/*.scala",
    "src/main/scala/model/*.scala",
    "src/main/scala/util/*.scala",
    "src/main/scala/view/IView.scala",
    "src/main/scala/view/Tui.scala",
    "src/main/scala/di/*.scala"
  ]

  thresholds {
    high = 100
    low = 100
  }

  reporters = ["html", "console"]
}
